
export default function About() {
  return (
    <>
    <div className='about'>
    <h2>About</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Interdum velit euismod in pellentesque massa placerat duis. Fermentum et sollicitudin ac orci. Augue ut lectus arcu bibendum at varius. Curabitur vitae nunc sed velit. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Imperdiet proin fermentum leo vel. Commodo ullamcorper a lacus vestibulum sed arcu non. Quam vulputate dignissim suspendisse in est ante in nibh. Senectus et netus et malesuada fames ac turpis egestas. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Mi in nulla posuere sollicitudin aliquam ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Pretium quam vulputate dignissim suspendisse in est ante. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Augue lacus viverra vitae congue eu consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Interdum velit euismod in pellentesque massa placerat duis. Fermentum et sollicitudin ac orci. Augue ut lectus arcu bibendum at varius. Curabitur vitae nunc sed velit. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Imperdiet proin fermentum leo vel. Commodo ullamcorper a lacus vestibulum sed arcu non. Quam vulputate dignissim suspendisse in est ante in nibh. Senectus et netus et malesuada fames ac turpis egestas. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Mi in nulla posuere sollicitudin aliquam ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Pretium quam vulputate dignissim suspendisse in est ante. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Augue lacus viverra vitae congue eu consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Interdum velit euismod in pellentesque massa placerat duis. Fermentum et sollicitudin ac orci. Augue ut lectus arcu bibendum at varius. Curabitur vitae nunc sed velit. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Imperdiet proin fermentum leo vel. Commodo ullamcorper a lacus vestibulum sed arcu non. Quam vulputate dignissim suspendisse in est ante in nibh. Senectus et netus et malesuada fames ac turpis egestas. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Mi in nulla posuere sollicitudin aliquam ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Pretium quam vulputate dignissim suspendisse in est ante. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Augue lacus viverra vitae congue eu consequat.</p>
    
    </div>
   </>
  )
}
